### ISSUE TITLE
能让歌词竖着放置吗？和酷狗的排放差不多

### ISSUE THREAD

**Issue by woqulegenicheng** [tuberry/desktop-lyric#1]

**Comment by tuberry** [comment]
中日韩文字竖排没什么问题，但西文或混合文本不适合竖排。酷狗怎么处理这类情况的？

**Comment by woqulegenicheng** [comment]
![image](https://user-images.githubusercontent.com/34201719/117299870-922d1200-aeab-11eb-91a4-0d4123106b82.png)
其实没有什么特殊处理，就这么用就可以，此外要是能在gnome-panel上显示也挺不错的，毕竟没有全局菜单的情况下panel基本上也没什么内容。

**Comment by tuberry** [comment]
图中英文字符方向是不一样的，如果中英文混合就比较麻烦。我周末看看吧。

放顶栏的话，把字体调小些再把歌词拖动相应位置效果也差不多。
