### ISSUE TITLE
[Bug] Compatibility with other extensions

### ISSUE THREAD

**Issue by mechtifs** [tuberry/desktop-lyric#14]
```js
// extension.js

...
class DesktopLyric {
    constructor() {
        ...
        Main.overview.connectObject('showing', () => (this.view = true),
            'hiding', () => (this.view = false), this);
        ...
    }
     ...
}
...
```

^ For some reason, this line of code is creating an unexpected issue.

**Steps to reproduce:**

- Create an extension that receives `showing` signal

  ```js
  // test1 extension.js
  
  const Main = imports.ui.main;
  
  class Extension {
	  constructor() {}
  
	  enable() {
		  Main.overview.connectObject(
			  'showing', () => log('test1 SHOWING'),
			  'shown', () => log('test1 SHOWN'),
			  'hiding', () => log('test1 HIDING'),
			  'hidden', () => log('test1 HIDDEN'), this);
	  }
  
	  disable() {
          Main.overview.disconnectObject(this);
	  }
  }
  
  function init() {
	  return new Extension();
  }
  ```

- Log in with both test1 and desktop-lyric enabled, then spam `Super` key (or any other method to open up and close overview)

  Output from `journalctl -f -o cat /usr/bin/gnome-shell`:
  ```
  test1 SHOWING
  test1 SHOWN
  test1 HIDING
  test1 HIDDEN
  test1 SHOWING
  test1 SHOWN
  test1 HIDING
  test1 HIDDEN
  ...
  ```

- Re-enable test1, then spam `Super` key again

  Output from `journalctl -f -o cat /usr/bin/gnome-shell`:
  ```
  test1 SHOWN
  test1 HIDING
  test1 HIDDEN
  test1 SHOWN
  test1 HIDING
  test1 HIDDEN
  ...
  ```
  
  The `test1 SHOWING` line is clearly missing, and this affects both X11 and Wayland sessions.

With desktop-lyric disabled, I've tested out other combinations between test1 and test2 below, which didn't reproduce the same issue.

```js
// test2 extension.js

const Main = imports.ui.main;

class Test {
	constructor() {
		Main.overview.connectObject(
			'showing', () => log('test2 SHOWING'),
			'shown', () => log('test2 SHOWN'),
			'hiding', () => log('test2 HIDING'),
			'hidden', () => log('test2 HIDDEN'), this);
	}

	destroy() {
        	Main.overview.disconnectObject(this);
	}
}

class Extension {
	constructor() {}

	enable() {
        	this._ext = new Test();
	}

	disable() {
        	this._ext.destroy();
		this._ext = null;
	}
}

function init() {
	return new Extension();
}

```

To be fair, no one is re-enabling extensions all the time. However GNOME will re-enable all extensions if woken up from hibernation. This issue is kinda annoying to say the least, however I couldn't locate where is actually causing the issue.

Test environments:
- kernel 6.1.12
- gnome-shell 43.3
- desktop-lyric 46a5b8f - 43c0a3f

**Comment by tuberry** [comment]
Nice catch!
I neglect `true` is a [special returned value](https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/Signals.md#connectname-callback) in `connect()`. It could be reproduced by:
```js
() => { log('test2 SHOWING'); return true; }
```
But the affection to other connects might be an upstream bug.

**Comment by mechtifs** [comment]
Great job!! Absolutely amazed by your work!

> But the affection to other connects might be an upstream bug.

Yeah I think so, since it only affects the `showing` signal. Strange bug tho.

**Comment by tuberry** [comment]
> But the affection to other connects might be an upstream bug.

Sorry, I misread the doc:

> If callback returns true, emission will stop and no other handlers will be invoked.

That affection is expected behavior. :)
