### ISSUE TITLE
装完后提示错误，是否需要手动安装其它依赖

### ISSUE THREAD

**Issue by inoton** [tuberry/desktop-lyric#3]
装完后提示错误，如下图。是不是缺少其它依赖导致的？
<img src="https://github.com/inoton/Bright/blob/main/2021-05-16_14-44.png?raw=true">

OS Name: Fedora 34
Kernel：5.12.3-300.fc34.x86_64
OS type: 64bit
GNOME Shell 40.1
Windowing System: X11

**Comment by tuberry** [comment]
打开`扩展`应用程序查看错误详情。可以尝试注销后登录看还有没有问题。

**Comment by inoton** [comment]
谢谢！修复了，研究下怎么用😄

Fedora 34 requires the "gnome-menus" dependency to be installed.
~ $ sudo dnf install gnome-menus

Error before fix：
Requiring GMenu, version none: Typelib file for namespace 'GMenu' (any version) not found.
