### ISSUE TITLE
Error on Install extension

### ISSUE THREAD

**Issue by Tarciano-Dias** [tuberry/desktop-lyric#4]
During installation that extension on page gnome extensions on firefox, I opened extension configuration widow and appears this message.  
![image](https://user-images.githubusercontent.com/56417475/118582516-d650ca00-b769-11eb-9417-6a5bdb26270d.png)

The message is below:

The settings of extension desktop-lyric@tuberry had an error:
```
SyntaxError: expected expression, got '.'
```

Stack trace:
```
@/home/tarciano/.local/share/gnome-shell/extensions/desktop-lyric@tuberry/prefs.js:10:12
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by tuberry** [comment]
What's the environment info? Did you try to re-login?

**Comment by Tarciano-Dias** [comment]
> What's the environment info? Did you try to re-login?

Yes, I did.
My environment infos:
![image](https://user-images.githubusercontent.com/56417475/118732913-af4dd300-b811-11eb-8e8a-5cb884bc1f71.png)

**Comment by tuberry** [comment]
Sorry, this extension only supports the latest stable branch of gnome upstream (now it's 40). It has supported gnome 3.38, but further backward compatibility is not guaranteed.
