### ISSUE TITLE
无法在 Activities 界面下拖动窗口到上/下一桌面

### ISSUE THREAD

**Issue by mechtifs** [tuberry/desktop-lyric#7]
如图中所演示：
![Screencast_10-23-2021_09:22:37 PM](https://user-images.githubusercontent.com/18751876/138558401-2ec5ed9d-7c68-45e0-8fa2-e8909200218a.gif)

**Comment by mechtifs** [comment]
好吧即使更新至 GNOME 41 也无法修复这个玄学问题（
感觉应该和特定 DPI 有关，相当迷惑。

**Comment by tuberry** [comment]
复现了。我觉得非 reactive 的 Actor 不应该作为 DND 的目标，但是上游[不](https://github.com/GNOME/gnome-shell/blob/c3f5aa6c5c4d06acd89837119cbe380f092cae67/js/ui/dnd.js#L615)这么想。我想可以在概览里隐藏来解决此问题。你那点`Hide Lyric`后还能复现吗？

**Comment by mechtifs** [comment]
感谢回复！
> 你那点`Hide Lyric`后还能复现吗？
确实无法复现。
