### ISSUE TITLE
Not working on Arch

### ISSUE THREAD

**Issue by caglarbingol** [tuberry/desktop-lyric#8]
is there some package i should install? 

and second can you put lyrics to top bar? i would be perfection.

**Comment by tuberry** [comment]
Sorry for late reply.

> is there some package i should install?

It has no external dependencies, but the online lyrics are all downloaded from 163 (i.e. http://music.163.com/api/search/pc?s=Maps&type=1&limit=1), so the corresponding lyrics may be missing.

> and second can you put lyrics to top bar? i would be perfection.

You may consider setting the right font and dragging the widget to the right position.
