### ISSUE TITLE
I mean the lyrics source

### ISSUE THREAD

**Issue by olivertzeng** [tuberry/desktop-lyric#9]
I really recommend music match. Not to start a war here but I think downloading lyrics from a Chinese website isn't safe and especially because I'm a Taiwanese, hoping that Winnie Xi won't use phishing attacks through that webease website.

**Comment by tuberry** [comment]
[MusicMatch](https://www.musixmatch.com/), If that you mean, requires [registration for an API key](https://developer.musixmatch.com/documentation) to access, which is not public or available enough.

As for security issues, the source code is GPLv3 licensed and publicly auditable. By the way, it is submitted to [e.g.o](https://extensions.gnome.org/extension/4006/desktop-lyric/) and [carefully reviewed](https://extensions.gnome.org/about/):
> All extensions uploaded to this site are carefully reviewed for malicious behavior before they are made available for download. This process of code review is similar to the process for Firefox add-ons submitted to[ addons.mozilla.org](https://addons.mozilla.org/).

Hope that can help.
